import React, { useState } from "react"
import Head from "next/head"
import Link from 'next/Link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faHome, faSun, faMoon } from "@fortawesome/free-solid-svg-icons";

class Header extends React.Component {
    state = {
        dark: true
    }

    componentDidMount() {
        if (localStorage.getItem('theme') === 'white') {
            document.body.classList.add('white-mode')
            this.setState({ dark: false })
        }
    }

    onChangeTheme = (event) => {
        if (localStorage.getItem('theme') === 'white') {
            document.body.classList.remove('white-mode')
            localStorage.setItem('theme', 'dark')
            this.setState({ dark: true })
        } else {
            document.body.classList.add('white-mode')
            localStorage.setItem('theme', 'white')
            this.setState({ dark: false })
        }
    }

    render(props) {
        return (
            <>
                <Head>
                    <title>{this.props.title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
    
                <nav>
                    <Link href='/'>
                        <a className='nav-item'><FontAwesomeIcon icon={faHome}/></a>
                    </Link>
    
                    <Link href='/projects'>
                        <a className='nav-item'>Projects</a>
                    </Link>
                    
                    <Link href='/education'>
                        <a className='nav-item'>Education</a>
                    </Link>
                    
                    <Link href='/about'>
                        <a className='nav-item'>About Me</a>
                    </Link>
    
                    <div style={{float: 'right', cursor: 'pointer'}} onClick={this.onChangeTheme}>
                        <FontAwesomeIcon icon={this.state.dark ? faSun : faMoon} />
                    </div>
                </nav>
            </>
        );
    }
    
};

export default Header;